### ISSUE TITLE
Repository Setup

### ISSUE THREAD

**Issue by pchlap** [AustralianCancerDataNetwork/pydicer#1]
@rnfinnegan @dalmouiee @ayhaidar @XiaoshuiHuang I've created a repo for our new tool. Here is a checklist of things to get things set up initially. Feel free to add to this and we can discuss in our new meeting.

- [x] Add open source licence (Apache)
- [x] define Python module structure
- [x] requirements.txt and requirements-dev.txt
- [x] .vscode set up for those developing in VSCode
- [x] pytest framework set up
- [x] github pipelines for running of tests
- [x] sphinx documentation set up
- [ ] setup.py for installation of library via pip
- [x] preparation of test data (not added directly to this repo though)
- [x] prepare pylint (including .pylintrc)

**Comment by dalmouiee** [comment]
I don't have permission to write to the repository, forked version was created through vscode when I tried pushing
