### ISSUE TITLE
patient-specific summary file

### ISSUE THREAD

**Issue by dalmouiee** [AustralianCancerDataNetwork/pydicer#122]
document patient journey through pipeline

**Comment by shivaniSkumar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/AusCAT-631835ddb47e6300129239fb/issues/AustralianCancerDataNetwork/pydicer/122?planning-poker) with Zenhub @anees-amir @dalmouiee @Janetxxx @LoisHolloway @mffield @pchlap
