### ISSUE TITLE
Prepare Pydicer documentation outline and overview

### ISSUE THREAD

**Issue by pchlap** [AustralianCancerDataNetwork/pydicer#125]
Outline of documentation provided for PyDicer (list examples etc).

**Comment by shivaniSkumar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/AusCAT-631835ddb47e6300129239fb/issues/AustralianCancerDataNetwork/pydicer/125?planning-poker) with Zenhub @anees-amir @fahimirfanalam @LoisHolloway @pchlap

**Comment by pchlap** [comment]
Proposed documentation outline:

- Home
- Examples
  - Getting Started
  - Working with Converted Data
  - Dataset Cleaning
  - Data Analysis
  - nnUNet Training
  - Auto-segmentation Inference
- Guides
  - Configuration
- Developers
  - Contributing
  - Code of Conduct
- Reference
- Input
  - Configuration
  - Preprocessing
  - Conversion
  - Visualisation
  - Dataset Preparation
  - Generation
  - Analyse
