### ISSUE TITLE
ASMIRT Workshop: Prepare Python basics Notebook

### ISSUE THREAD

**Issue by pchlap** [AustralianCancerDataNetwork/pydicer#128]
A Jupyter notebook to run on Google CoLab to work through some basic Python concepts

**Comment by shivaniSkumar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/AusCAT-631835ddb47e6300129239fb/issues/AustralianCancerDataNetwork/pydicer/128?planning-poker) with Zenhub @anees-amir @dalmouiee @fahimirfanalam @Janetxxx @LoisHolloway @mffield @pchlap
