### ISSUE TITLE
Release v0.1.0

### ISSUE THREAD

**Issue by pchlap** [AustralianCancerDataNetwork/pydicer#129]
Release first version of pydicer to pypi.

**Comment by shivaniSkumar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/AusCAT-631835ddb47e6300129239fb/issues/AustralianCancerDataNetwork/pydicer/129?planning-poker) with Zenhub @dalmouiee @fahimirfanalam @Janetxxx @LoisHolloway @pchlap
