### ISSUE TITLE
Prepare ESTRO Poster

### ISSUE THREAD

**Issue by pchlap** [AustralianCancerDataNetwork/pydicer#131]

**Comment by shivaniSkumar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/AusCAT-631835ddb47e6300129239fb/issues/AustralianCancerDataNetwork/pydicer/131?planning-poker) with Zenhub @anees-amir @dalmouiee @fahimirfanalam @Janetxxx @LoisHolloway @mffield @pchlap
