### ISSUE TITLE
Provide user friendly structure overview for nnUNet

### ISSUE THREAD

**Issue by pchlap** [AustralianCancerDataNetwork/pydicer#132]
Determine structure names in dataset to define standard mapping and then use structure standardisation to map across modules.

**Comment by shivaniSkumar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/AusCAT-631835ddb47e6300129239fb/issues/AustralianCancerDataNetwork/pydicer/132?planning-poker) with Zenhub @anees-amir @dalmouiee @fahimirfanalam @LoisHolloway @pchlap
