### ISSUE TITLE
Implement auto-seg analysis

### ISSUE THREAD

**Issue by pchlap** [AustralianCancerDataNetwork/pydicer#135]
After auto-segmentation is applied to data in the dataset, use the structure name mappings to determine matching structures between an autosegmentation and a reference structure set. Computer metrics and provide standard analysis (tables, plots).

**Comment by shivaniSkumar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/AusCAT-631835ddb47e6300129239fb/issues/AustralianCancerDataNetwork/pydicer/135?planning-poker) with Zenhub @anees-amir @fahimirfanalam @LoisHolloway @pchlap @dalmouiee
