### ISSUE TITLE
ASMIRT Workshop: Prepare DICOM Manipulation Notebook

### ISSUE THREAD

**Issue by pchlap** [AustralianCancerDataNetwork/pydicer#136]
Prepare a Jupyter notebook to run on Google CoLab to work through reading, manipulating and writing DICOM files.

**Comment by shivaniSkumar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/AusCAT-631835ddb47e6300129239fb/issues/AustralianCancerDataNetwork/pydicer/136?planning-poker) with Zenhub @anees-amir @dalmouiee @fahimirfanalam @Janetxxx @LoisHolloway @mffield @pchlap
