### ISSUE TITLE
ASMIRT Workshop: Prepare data conversion and dose metric analysis Notebook

### ISSUE THREAD

**Issue by pchlap** [AustralianCancerDataNetwork/pydicer#137]
A Juputer notebook to run on Google CoLab to run the PyDicer pipeline, compute some dose metrics on the dataset converted and plot these metrics.

**Comment by shivaniSkumar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/AusCAT-631835ddb47e6300129239fb/issues/AustralianCancerDataNetwork/pydicer/137?planning-poker) with Zenhub @anees-amir @dalmouiee @fahimirfanalam @Janetxxx @LoisHolloway @mffield @pchlap
