### ISSUE TITLE
Prepare theory overview slides for ASMIRT Workshop

### ISSUE THREAD

**Issue by pchlap** [AustralianCancerDataNetwork/pydicer#138]
Slides needed for:

## Python Overview
- How to install Python / run Python code
- What is Jupyter and Google CoLab
- Python Syntax basics
- Pandas DataFrames and plotting overview

## DICOM Overview
- Brief description of DICOM
- Overview of CT, RTSTRUCT, RTPLAN and RTDOSE modalities

## Data conversion and analysis
- Motivation as to why to convert data away from DICOM
- Brief explanation of what the PyDicer tool does

**Comment by shivaniSkumar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/AusCAT-631835ddb47e6300129239fb/issues/AustralianCancerDataNetwork/pydicer/138?planning-poker) with Zenhub @anees-amir @dalmouiee @fahimirfanalam @Janetxxx @LoisHolloway @mffield @pchlap
