### ISSUE TITLE
ASMIRT Workshop: Test run

### ISSUE THREAD

**Issue by pchlap** [AustralianCancerDataNetwork/pydicer#139]
Have a test run with some RTs (Shivani? Open up to others who are interested?) of the ASMIRT workshop end-to-end.

**Comment by pchlap** [comment]
1.5 hours session booked for Thursday (20th) morning.

**Comment by shivaniSkumar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/AusCAT-631835ddb47e6300129239fb/issues/AustralianCancerDataNetwork/pydicer/139?planning-poker) with Zenhub @anees-amir @dalmouiee @fahimirfanalam @Janetxxx @LoisHolloway @mffield @pchlap
