### ISSUE TITLE
Checking for missing data integrities

### ISSUE THREAD

**Issue by dalmouiee** [AustralianCancerDataNetwork/pydicer#14]
(what to do, to quarantine, then correct?)

- Missing slices 
- Missing header information
- Corrupt data
- Strange RT struct data

**Comment by pchlap** [comment]
Another thing that can go wrong here is duplicated images/series... How to handle?

**Comment by dalmouiee** [comment]
Related to #13

**Comment by dalmouiee** [comment]
As new issues are identified, will open new issues, closing this
