### ISSUE TITLE
Prepare template for components documentation

### ISSUE THREAD

**Issue by pchlap** [AustralianCancerDataNetwork/pydicer#140]
A template containing sub-sections for component documentation should be prepared. Types of subsections might be:
- Overview
- Configuration
- Access, Authentication, Secrets
- Docker Image
- Troubleshooting

**Comment by shivaniSkumar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/AusCAT-631835ddb47e6300129239fb/issues/AustralianCancerDataNetwork/pydicer/140?planning-poker) with Zenhub @anees-amir @dalmouiee @fahimirfanalam @Janetxxx @LoisHolloway @mffield @pchlap
