### ISSUE TITLE
Imaging visualiser

### ISSUE THREAD

**Issue by dalmouiee** [AustralianCancerDataNetwork/pydicer#15]
Produce image visualisations on converted data

**Comment by rnfinnegan** [comment]
When to save images:
- after conversion: (configurable) each image modality, contours (on referenced series), doses (on referenced series)

**Comment by dalmouiee** [comment]
PET overlay on the CT

**Comment by dalmouiee** [comment]
New potential feature: write metadata about image in top-right white space for the image visualiser
