### ISSUE TITLE
Function to run pipeline

### ISSUE THREAD

**Issue by dalmouiee** [AustralianCancerDataNetwork/pydicer#17]
- Configurations (ie. input method)

**Comment by pchlap** [comment]
Sorry @dalmouiee 

I inadvertently merged some code I was working on this without review (committed it to the dicom input branch)...

You can have a look at it, it is in pydicer/pipeline.py for now. It allows us to run the whole test pipeline using:

```
python -m pydicer.pipeline
```

Will be useful for development and we can improve on it as we add in more configuration options etc.

**Comment by dalmouiee** [comment]
No problem @pchlap , I figured that the pipeline function was for running the test via script, that'll be great during development. Great job on it!
