### ISSUE TITLE
Future README/CONTRIBUTING guides

### ISSUE THREAD

**Issue by pchlap** [AustralianCancerDataNetwork/pydicer#38]
Some suggestions for future improvements in #37 thanks to @dalmouiee:

- [ ] Quick examples of using the specific modules without the pipeline in case others wish to them alone. Although the Sphinx documentation might solve this, I personally like reading quick examples from a repo, without diving too deep into docs
- [ ] Possibly we could add some kind of diagram to summarise that "pyDicer Pipeline" section, I like diagrams!
- [ ] Might be worth while having a new WIP PR to monitor/contribute to future READMEs?

**Comment by dalmouiee** [comment]
- Updating README
- Example Jupyter notebook with the docs

**Comment by dalmouiee** [comment]
Aim for initial release on PyPI (alpha version, 0.1.0), on coding club to demo this
