### ISSUE TITLE
Setup pytest and github pipelines

### ISSUE THREAD

**Issue by pchlap** [AustralianCancerDataNetwork/pydicer#4]

**Comment by pchlap** [comment]
Hey @dalmouiee, when you implement the github pipelines, could you also try to run pylint as part of that pipeline (as well as pytest)?

**Comment by dalmouiee** [comment]
Yep I've also tried running the pipeline for multiple versions of Python (3.6-3.9). Got some interesting results you might want to check out #28

**Comment by dalmouiee** [comment]
> Hey @dalmouiee, when you implement the github pipelines, could you also try to run pylint as part of that pipeline (as well as pytest)?

@pchlap Yep I've also tried running the pipeline for multiple versions of Python (3.6-3.9). Got some interesting results you might want to check out #28

**Comment by dalmouiee** [comment]
Pipeline for running Pylint and pytest for main branch merges has been activated. Only python3.7 and 3.8 are included in the tests, having issues with 3.6 and 3.9 related to Pydicom/Platipy/Pymedphys versioning, when attempting to install them via pip. Investigating this issue in #29
