### ISSUE TITLE
Consider pandas dataframe as datastructure between modules

### ISSUE THREAD

**Issue by pchlap** [AustralianCancerDataNetwork/pydicer#40]
I was just thinking that a Pandas DataFrame might be a nice, consistent, way to hold the data as we pass it from module to module.

The nice thing about this would be that its easy to save off (even to something like a csv). But especially if there is ever a dashboard to monitor/control this tool, pandas plays very nicely with Dash.

The downside is that a dataframe doesn't have the hierarchy that we get with a simple dict. But that can be overcome by using groupby etc...

Something to discuss in our next meeting.

**Comment by dalmouiee** [comment]
I appreciate this from a dashboarding perspective, also operations on dataframes are optimised better than say dictionaries. I guess for hierarchy and nesting info, we could have pointers to other dataframes but not sure if that'll scale well and how complex it may get.

**Comment by pchlap** [comment]
> A potential solution built into Pandas is a [multiindex dataframe](https://pandas.pydata.org/pandas-docs/stable/user_guide/advanced.html), which is essentially a hierarchy dataframe 

I love this idea @dalmouiee . We can discuss in more detail when meet tomorrow :)
